version: '3'

services:
  woeden_agent:
    build:
      context: .
    network_mode: host
    ipc: host
    environment:
      - HOST=localhost
      # - ROS_DISCOVERY_SERVER=127.0.0.1:11811 # for testing discovery server
    volumes:
      - ./woeden:/woeden

volumes:
  woeden: