version: '3'

services:
  woeden_agent:
    build:
      context: .
    network_mode: host
    ipc: host
    environment:
      - MQTT_HOST=localhost
    volumes:
      - ./woeden:/woeden

volumes:
  woeden: