version: '3'

services:

  sensorsurf_agent:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    network_mode: host
    user: 1000:1000
    environment:
      - MQTT_HOST=ssl://mqtt.woeden.com
    volumes:
      - ~/woeden:/woeden
      - /dev/shm:/dev/shm

  talker:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp talker
    network_mode: host
    user: 1000:1000

volumes:
  woeden:
