name: Deploy woeden-agent to ECR

on:
  push:
    branches: [ "master" ]

env:
  # NOTE this MUST be us-east-1 because this is where all public repositories live.
  # Private ones can go in the normal AWS region for the rest of the relevant infra.
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        # TODO: switch to repo secret when have access
        aws-access-key-id: AKIAZHJGIKOLWZZSKLTC
        aws-secret-access-key: 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

    # NOTE: have to do slightly different syntax for private repo, this is for public!
    # See https://github.com/aws-actions/amazon-ecr-login
    - name: Login to Amazon ECR
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Build and push
      uses: docker/build-push-action@v4
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: my-ecr-public-registry-alias
        REPOSITORY: agent
        IMAGE_TAG: ${{ github.sha }}
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.REGISTRY_ALIAS }}/${{ env.REPOSITORY }}:latest 
          ${{ env.REGISTRY }}/${{ env.REGISTRY_ALIAS }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} 
